[simulation]
base_path = "./fake-short"
start_time = 2027-01-01T00:00:00
duration_s = "1 hour"
num_of_obs_per_detector = 60

[scanning_strategy]
spin_sun_angle_deg = 5
spin_boresight_angle_deg = 85
precession_period_min = 43800 # One month
spin_rate_rpm = 1

[planet_scanning]
spin2ecl_delta_time_s = 5.0
planet_name = "jupiter"
output_table_file_name = "observation_time_table.txt"
output_map_file_name = "map.fits.gz"
output_nside = 32
sampling_rate_hz = 1.0

[[detectors]]
channel_obj = "/releases/v1.0/satellite/LFT/L1-040/info"
