[simulation]
base_path = "./fake-jupiter-44GHz"
start_time = 2027-01-01T00:00:00
duration_s = "1460 days" # 4 years
num_of_obs_per_detector = 14600

[scanning_strategy]
spin_sun_angle_rad = 0
precession_period_min = 1e15 # No precession
spin_rate_rpm = 0.01
spin_boresight_angle_rad = 0.0

[planet]
planet_name = "jupiter"
sed_file_name = "jupiter_sed_ghz_k.csv"
planet_radius_m = 7.1492e7
scanning_simulation = "./fake-short"

[detector]
# Parameters taken from Planck 2018 II, table 1 (pag. 3)
name = "planck30GHz"
channel = "30 GHz"
fwhm_arcmin = 33.10
fknee_mhz = 113.9
bandwidth_ghz = 9.89
bandcenter_ghz = 28.4
sampling_rate_hz = 1.0
