[simulation]
base_path = "./litebird-jupiter-040GHz"
num_of_mc_runs = 500

[planet]
planet_name = "jupiter"
sed_file_name = "jupiter_sed_ghz_k.csv"
planet_radius_m = 7.1492e7
scanning_simulation = "./litebird-scanning-strategy"

[detector]
channel_obj = "/releases/v1.0/satellite/LFT/L1-040/channel_info"
sampling_rate_hz = 1.0
