[simulation]
base_path = "./planck-jupiter-044GHz"

[planet]
planet_name = "jupiter"
sed_file_name = "jupiter_sed_ghz_k.csv"
planet_radius_m = 7.1492e7

[detector]
# Parameters taken from Planck 2018 II, table 1 (pag. 3)
name = "planck44GHz"
channel = "44 GHz"
fwhm_arcmin = 26.99
fknee_mhz = 53.0
bandwidth_ghz = 10.72
bandcenter_ghz = 44.1

# The number in the table is 174.0, but we're interested in the white
# noise for *one* RCA, which means we must multiply by √3, as there
# are 3 beams @ 44 GHz
net_ukrts = 301.3     
