[simulation]
base_path = "./short-scanning-strategy"
start_time = 2020-01-01T00:00:00
duration_s = "5 days"
num_of_obs_per_detector = 24

[scanning_strategy]
scanning_strategy_obj = "/releases/v1.0/satellite/scanning_parameters"
spin_boresight_angle_rad = 0.8726646259971648

[planet_scanning]
spin2ecl_delta_time_s = 60.0
planet_name = "jupiter"
output_nside = 1024
sampling_rate_hz = 1.0
